CHANGELOG.md
assets/manifest.json
package-lock.json
package.json
src/css/content.scss
src/js/module/K2pickerarea/K2PickerareaPicker.js

When we merged teams, we decided to get rid of the Demolition team and now that WAQ is over, I finally had some time to deal with the leftover code.
Part of https://github.com/Expensify/Expensify/issues/256949

Remove demolition related code from K2

---

CHANGELOG.md
README.md
assets/manifest.json
package-lock.json
package.json
src/js/module/dashboard/FormPassword.js

cc @tgolen 
This PR updates the instructions to open the K2 dashboard in the App repo, since the E/E repo is only for internal employees, and external contributors can't access it.
$ https://github.com/Expensify/Expensify/issues/260956
Tests:
1. Open https://github.com/Expensify/App#k2 and verify the K2 is loading
2. Update this [line](https://github.com/Expensify/k2-extension/blob/bfac2b97b70965297ca92107c87823860a54067c/src/js/module/dashboard/index.js#L52) to show the password form and verify the link opens the PAT instructions in a new tab:

Update link to open K2 for contributors

---

CHANGELOG.md
assets/manifest.json
package-lock.json
package.json
src/js/lib/api.js

Labels are broken as per $https://github.com/Expensify/Expensify/issues/262805
GH now added spaces on before and after the property we use to determine the repo (`#repository-container-header strong a`). I've added a trim to remove that.
1. Run project locally following [readme.md](https://github.com/Expensify/k2-extension)
2. Try to assign a label in a test issue clicking on our k2 extension buttons (you can use this one https://github.com/Expensify/Expensify/issues/262808)
https://user-images.githubusercontent.com/5818999/219220283-e8af1a7c-33b7-46b4-86ba-736998348281.mov

Fix Label assignment

---

src/js/component/panel-title/Title.js
src/js/module/dashboard/ListIssuesWAQ.js

I didn't notice the weeks for WAQ already had the numbers, so I fixed them and refactored them to use the new count.
Fixes https://github.com/Expensify/Expensify/issues/267129

Fix WAQ headers

---

CHANGELOG.md
assets/manifest.json
package-lock.json
package.json

I fixed a few security vulnerabilities below so we need to bump the version to publish them.
https://github.com/Expensify/k2-extension/pull/148
https://github.com/Expensify/k2-extension/pull/147
https://github.com/Expensify/k2-extension/pull/146
https://github.com/Expensify/k2-extension/pull/143

Bump version to account for vulnerability fixes

---

CHANGELOG.md
assets/manifest.json
package-lock.json
package.json
src/js/lib/api.js

Slack: https://expensify.slack.com/archives/C06N6E4RF/p1686913493813059
[getCurrentUser()](https://github.com/Expensify/k2-extension/blob/d43f5b1fc6e72f46f812017f0f06c7483074f300/src/js/lib/api.js#L23) was using the classes `.Header-link .avatar` and then fetching the value of the `alt` attribute in order to fetch the current user's Github username. But it looks like the parent CSS class was updated to `.AppHeader` and that led to k2 not being able to load the dashboard at all:
This is assuming the meta tag isn't really something that would change vs the class for the avatar which might change at some point

Update getCurrentUser() to fetch the current user's Github username from the meta tag instead of the avatar

---

assets/manifest.json

We're not using Chrome's Storage API and chrome.cookies, so let's remove them.
More context on Slack: https://expensify.slack.com/archives/C03TQ48KC/p1686931078184029?thread_ts=1686854265.325289&cid=C03TQ48KC

Remove unused permissions for storage and cookies Chrome APIs

---

CHANGELOG.md
assets/manifest.json
package-lock.json
package.json
src/js/lib/api.js

From slack: https://expensify.slack.com/archives/C06N6E4RF/p1687196296716529
The Github UI update led to broken label selectors since we're relying on CSS classes in the DOM but these are likely to change. Let's fetch the details we need to make API requests to Github from the url instead of the DOM.
Test issue here: https://github.com/Expensify/Expensify/issues/293348

Fetch repository name, owner and issue number from the current URL instead of relying on the DOM

---

CHANGELOG.md
assets/manifest.json
package-lock.json
package.json
src/js/lib/api.js

Improved the regex (that fetches repo name, owner and issue number) to also work for pull request URLs.
Test PR: https://github.com/Expensify/App/pull/21242

Fix for button to add PR checklist to pull requests

---

CHANGELOG.md
assets/manifest.json
package-lock.json
package.json
src/js/lib/actions/Issues.js

The regex was matching `tgolen</details>` which was keeping the k2 dashboard from showing the issues you are an owner of. With this change, it now properly matches only `tgolen` and will properly show the issues you own:

Fix the regex for issue owner to be more accurate

---

CHANGELOG.md
assets/manifest.json
package-lock.json
package.json
src/css/content.scss
src/js/module/dashboard/ListIssuesAssigned.js

$ https://github.com/Expensify/Expensify/issues/331612#issuecomment-1790759072

Keep issue filter text black in dark mode

---

CHANGELOG.md
assets/manifest.json
package-lock.json
package.json

I have been having issues with rate limiting on my PAT, and thought that the source of the issue might be KSv2. The Octokit SDK is supposed to have throttling best-practices built-in, but in the version of octokit we were using, it was commented-out: https://github.com/octokit/octokit.js/compare/v1.7.1...v3.1.1#diff-0b622e16b7fc8551bbe85cced944e28ed91560455e117bfd5a2ffb91fa2731b6L13
So this PR is just updating the octokit client to latest. I tested by:
- running `npm i && npm run build`
- then in `chrome://extensions` make sure developer mode is enabled in the top-left corner
- then press `Load Unpacked`, and choose the `dist` folder from k2-extension
- Then open K2 and refresh the page. It should all continue to work
- Open an issue and make sure the K2 sidebar appears as normal:

Update octokit client

---

CHANGELOG.md
assets/manifest.json
package-lock.json
package.json
src/js/lib/api.js

I noticed this error today, I have no idea why it all of a sudden started to show up. I updated the regex to make the issue/pull stuff optional, switched to using named capture groups, and protected against null matches.
I tested it to ensure all three URL types are passing the regex now:
https://regex101.com/r/369Aua/3

Update the regex to prevent errors on dashboard

---

assets/manifest.json

Context https://expensify.slack.com/archives/C06N6E4RF/p1699992960443509
I think we don't need that permission because we are not using url, pendingUrl, title, or favIconUrl.

Remove tabs permission

---

CHANGELOG.md
assets/manifest.json
package-lock.json
package.json

It's sad that `.7` is technically smaller than `.61` so updating it.

Fix version number for #181

---

CHANGELOG.md
assets/manifest.json
package-lock.json
package.json
src/js/component/list-item/ListItemIssue.js
src/js/component/panel/PanelIssues.js
src/js/lib/pages/github/issue.js
src/js/module/dashboard/Legend.js
src/js/module/dashboard/ListIssuesAssigned.js

Fixes https://github.com/Expensify/Expensify/issues/390841
1. Have a test issue like https://github.com/Expensify/Expensify/issues/390830
2. Assign it only to yourself
3. Verify you can set yourself as the code owner and you can toggle it on and off
4. Assign the issue to one more person and make them the code owner
5. Refresh your K2 dashboard and verify the issue is shown with an empty star 
6. Check the filter to hide "Owned by Someone Else"
7. Verify that the issues with an empty star are no longer shown

Show on the K2 dashboard when someone else is the issue owner

---

CHANGELOG.md
assets/manifest.json
package-lock.json
package.json
src/js/lib/pages/github/issue.js

Fixes https://github.com/Expensify/Expensify/issues/417562
- Have a GH issue open
- Add a comment
- Verify that the pickers in the sidebar are redrawn

Check every second to redraw pickers

---

assets/manifest.json
package-lock.json
package.json

Fixes https://github.com/Expensify/Expensify/issues/422655
Loading the plugin in Chrome after building produces no errors in console, which should be visible if there are any Manifest V3 incompatibilities. 
Tested as much as I could, but will appreciate another pair of eyes looking into this. Afterwards, we need to submit the beta to Google for review to see if it really passes Manifest V3 restrictions.
Migration steps checked out:

Updated K2 extension to Manifest V3

---

.github/workflows/lint.yml
CHANGELOG.md
assets/manifest-firefox.json
assets/manifest.json
package-lock.json
package.json

Fixed problems with the FF extension by using the `web-ext` package from Mozilla, which helps with linting. 
Web-ext linting was also added as a step to GitHub actions, so we can be sure it's compatible with Firefox without having to first package and upload to addons.mozilla.org.

Fixed manifest for Firefox, added linting and CI

---

CHANGELOG.md
assets/manifest-firefox.json
assets/manifest.json
package-lock.json
package.json
src/js/lib/pages/github/issue.js

This is part of https://github.com/Expensify/Expensify/issues/438990.
1. I manually added the comment to [this test issue](https://github.com/Expensify/Expensify/issues/439459#issuecomment-2442095992) which contains the copy checklist button
2. Click the button
3. Verify that the checklist is posted from your account

Add a copy bugzero checklist button to GH issues

---

README.md

Low priority but while updating my K2 recently I was confused that we tell the user to run `npm i` at the last even when that i necessary to generate the `dist` folder.

Update readme for better readability 

---

CHANGELOG.md
assets/manifest-firefox.json
assets/manifest.json
package-lock.json
package.json
src/js/lib/api.js
src/js/module/K2pickerarea/K2PickerareaPicker.js

Besides the main changes for HotPick, I removed the `Ops` label because it hasn't been used in more than a year.
1. Run `npm run web`
2. Update your local extension in from `chrome://extension`
3. Reload the K2 dashboard
4. Verify Expensify/Expensify Hot Pick issues are shown:
6. Open any issue, make sure the `Hot Pick` shortcut is shown in the right-hand menu:
----------
Fixes: https://github.com/Expensify/Expensify/issues/453292

Add HotPick E/E issues to K2 + Shortcut

---

CHANGELOG.md
assets/manifest-firefox.json
assets/manifest.json
package-lock.json
package.json
src/js/module/dashboard/ListIssuesAssigned.js

Derive initial checkbox state from query string

---

CHANGELOG.md
assets/manifest-firefox.json
assets/manifest.json
package-lock.json
package.json
src/js/ONYXKEYS.js
src/js/lib/actions/Issues.js
src/js/module/dashboard/ListIssuesAssigned.js

cc @cead22 
This PR refactors https://github.com/Expensify/k2-extension/pull/220 to store the information in Onyx so the settings are automatically remembered.
1. Go to the K2 dashboard
2. Check some of the checkbox filters for hiding specific issues
3. Refresh the page
4. Verify the same checkbox filters were remembered and applied to the dashboard

Move checkbox config to onyx

---

.github/workflows/snyk_pull_requests.yml

No need to use a third party action and melvin's GH token when GH should be able to do this with the CLI and built in actions token.
Fixes https://github.com/Expensify/Expensify/issues/455566

Use GH CLI to assign reviewer instead of melvin token

---

.github/workflows/lint.yml

Coming from https://expensify.slack.com/archives/CC7NECV4L/p1743022578963949, this pull request updates all mutable action references to use immutable commit hashes instead. This is a security measure to protect from supply chain attacks.

Pin GitHub Actions to immutable commit SHAs

---

CHANGELOG.md
assets/manifest-firefox.json
assets/manifest.json
package-lock.json
package.json

Follow up to this PR [Fix K2 prioritization for large lists](https://github.com/Expensify/k2-extension/pull/257#top) because I forgot to update the version.

Bump version for prioritization fix on large lists

---

CHANGELOG.md
assets/manifest-firefox.json
assets/manifest.json
package.json
src/js/component/list-item/ListItemIssue.js
src/js/component/panel/PanelIssues.js
src/js/lib/actions/Issues.js
src/js/module/dashboard/ListIssuesAssigned.js

Ever wanted to see only your overdue issues? Now you can!
Brought to you primarily by Cursor and vibe coding, which is neat.

Add Not Overdue filter
